
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en-US" prefix="og: http://ogp.me/ns#" class="ie8"> <![endif]-->
<!--[if !IE]><!--> <html lang="en-US" prefix="og: http://ogp.me/ns#"> <!--<![endif]-->
<head>
<meta name="msvalidate.01" content="C52810F00EB501F89887A00122863B0A" />	
<script src="https://www.kenyt.ai/botapp/ChatbotUI/dist/js/bot-loader.js" type="text/javascript" data-bot="55438071"></script>	
	
<!-- Global site tag (gtag.js) - Google Ads: 454762883 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-454762883"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-454762883');
  
 <!-- Google Tag Manager Code Added 30-4-21-->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-53D399H');</script>
<!-- End Google Tag Manager -->
 
</script>
	
	
	
	
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" rel="stylesheet" crossorigin="anonymous">

<meta name="msapplication-TileColor" content="">
<meta name="theme-color" content="">

<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="https://www.cdi.org.in/xmlrpc.php">
	<link rel="canonical" href="https://crunchify.com/how-to-create-social-sharing-button-without-any-plugin-and-script-loading-wordpress-speed-optimization-goal/">

<title>Best Diabetologist in Pune - Chellaram Multispeciality Hospital</title>

<!-- This site is optimized with the Yoast SEO plugin v9.3 - https://yoast.com/wordpress/plugins/seo/ -->
<meta name="description" content="Looking for Best Diabetologist in Pune? Chellaram Hospital provides the best diabetology department with qualified doctors. Get Consultation Now"/>
<link rel="canonical" href="https://www.cdi.org.in/department/diabetology/" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Best Diabetologist in Pune - Chellaram Multispeciality Hospital" />
<meta property="og:description" content="Looking for Best Diabetologist in Pune? Chellaram Hospital provides the best diabetology department with qualified doctors. Get Consultation Now" />
<meta property="og:url" content="https://www.cdi.org.in/department/diabetology/" />
<meta property="og:site_name" content="Chellaram Hospital" />
<meta property="article:publisher" content="https://www.facebook.com/ChellaramHospital" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="Looking for Best Diabetologist in Pune? Chellaram Hospital provides the best diabetology department with qualified doctors. Get Consultation Now" />
<meta name="twitter:title" content="Best Diabetologist in Pune - Chellaram Multispeciality Hospital" />
<meta name="twitter:image" content="https://www.cdi.org.in/wp-content/uploads/2017/11/diebatology-1.png" />
<!-- / Yoast SEO plugin. -->

<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="Chellaram Hospital &raquo; Feed" href="https://www.cdi.org.in/feed/" />
<link rel="alternate" type="application/rss+xml" title="Chellaram Hospital &raquo; Comments Feed" href="https://www.cdi.org.in/comments/feed/" />
<link rel='stylesheet' id='aptf-bxslider-css'  href='https://www.cdi.org.in/wp-content/plugins/accesspress-twitter-feed/css/jquery.bxslider.css?ver=1.5.8' type='text/css' media='all' />
<link rel='stylesheet' id='aptf-front-css-css'  href='https://www.cdi.org.in/wp-content/plugins/accesspress-twitter-feed/css/frontend.css?ver=1.5.8' type='text/css' media='all' />
<link rel='stylesheet' id='aptf-font-css-css'  href='https://www.cdi.org.in/wp-content/plugins/accesspress-twitter-feed/css/fonts.css?ver=1.5.8' type='text/css' media='all' />
<link rel='stylesheet' id='contact-form-7-css'  href='https://www.cdi.org.in/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.0.4' type='text/css' media='all' />
<link rel='stylesheet' id='theme.css-css'  href='https://www.cdi.org.in/wp-content/plugins/popup-builder/public/css/theme.css?ver=3.0.7' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-layout-css'  href='https://www.cdi.org.in/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=3.5.9' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-smallscreen-css'  href='https://www.cdi.org.in/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=3.5.9' type='text/css' media='only screen and (max-width: 768px)' />
<link rel='stylesheet' id='woocommerce-general-css'  href='https://www.cdi.org.in/wp-content/plugins/woocommerce/assets/css/woocommerce.css?ver=3.5.9' type='text/css' media='all' />
<style id='woocommerce-inline-inline-css' type='text/css'>
.woocommerce form .form-row .required { visibility: visible; }
</style>
<link rel='stylesheet' id='wcqi-css-css'  href='https://www.cdi.org.in/wp-content/plugins/woocommerce-quantity-increment/assets/css/wc-quantity-increment.css?ver=4.9.18' type='text/css' media='all' />
<link rel='stylesheet' id='wp-pagenavi-css'  href='https://www.cdi.org.in/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.70' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-ladda-min-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/css/ladda.min.css?ver=16.3' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-customer-profile-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-addon-pro/frontend/modules/customer_profile/resources/css/customer_profile.css?ver=1.1' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-intlTelInput-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/css/intlTelInput.css?ver=16.3' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-picker-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/css/picker.classic.css?ver=16.3' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-picker-date-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/css/picker.classic.date.css?ver=16.3' type='text/css' media='all' />
<link rel='stylesheet' id='bookly-main-css'  href='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/css/bookly-main.css?ver=16.3' type='text/css' media='all' />
<link rel='stylesheet' id='font-awesome-css'  href='https://www.cdi.org.in/wp-content/plugins/js_composer/assets/lib/bower/font-awesome/css/font-awesome.min.css?ver=5.5.2' type='text/css' media='all' />
<link rel='stylesheet' id='bootstrap-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/bootstrap.min.css?ver=3.3.6' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/owl.carousel.min.css?ver=2.2.1' type='text/css' media='all' />
<link rel='stylesheet' id='dcalendar-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/dcalendar.min.css?ver=1.4' type='text/css' media='all' />
<link rel='stylesheet' id='clockpicker-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/jquery-clockpicker.min.css?ver=0.0.7' type='text/css' media='all' />
<link rel='stylesheet' id='simple-line-icons-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/simple-line-icons.css?ver=4.6.3' type='text/css' media='all' />
<link rel='stylesheet' id='magnific-popup-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/magnific-popup.min.css?ver=1.4' type='text/css' media='all' />
<link rel='stylesheet' id='nice-select-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/nice-select.min.css?ver=1.0' type='text/css' media='all' />
<link rel='stylesheet' id='swiper-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/swiper.min.css?ver=3.4.0' type='text/css' media='all' />
<link rel='stylesheet' id='animate-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/animate.min.css?ver=3.4.0' type='text/css' media='all' />
<link rel='stylesheet' id='meanmenu-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/meanmenu.css?ver=2.0.7' type='text/css' media='all' />
<link rel='stylesheet' id='cosgrove-style-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/styles.css?ver=1.4' type='text/css' media='all' />
<link rel='stylesheet' id='cosgrove-responsive-css'  href='https://www.cdi.org.in/wp-content/themes/cosgrove/assets/css/responsive.css?ver=1.4' type='text/css' media='all' />
<link rel='stylesheet' id='cosgrove-google-fonts-css'  href='//fonts.googleapis.com/css?family=Poppins%3A400%2C500%2C600%2C700%7CAsap%3A400%2C500%2C600%2C700%7COpen+Sans%3A400%2C500%2C600%2C700%7CRoboto%3A400%2C500%2C600%2C700&#038;subset=latin' type='text/css' media='all' />
<link rel='stylesheet' id='js_composer_front-css'  href='https://www.cdi.org.in/wp-content/plugins/js_composer/assets/css/js_composer.min.css?ver=5.5.2' type='text/css' media='all' />
<script type='text/javascript' src='https://www.cdi.org.in/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/accesspress-twitter-feed/js/jquery.bxslider.min.js?ver=1.5.8'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/accesspress-twitter-feed/js/frontend.js?ver=1.5.8'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var sgpbPublicUrl = "https:\/\/www.cdi.org.in\/wp-content\/plugins\/popup-builder\/public\/";
/* ]]> */
</script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/popup-builder/public/js/Popup.js?ver=3.0.7'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/popup-builder/public/js/PopupConfig.js?ver=3.0.7'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var SGPB_POPUP_PARAMS = {"popupTypeAgeRestriction":"ageRestriction","defaultThemeImages":{"1":"iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAADHElEQVQ4jaWVQU8bRxiGHxYHrwdbHW8gFhU5IKurWM0plTiQC1SqUFD6C7hEorfmSv9ChBC39NZDFCm3xrkl6gWoKjBCizgRoS0uh0Y1BjQ7ks3sGkK2B2MLY4dE7Xvd93v0zXzfvNsXxzG9VKlUprXWk8aYceAOkAOqwK4QYlNKuToyMvJbr9q+q1Ct9bflcvkRMCuEsNKZDIn+\/vb39+fn1Gs1jDEfgBf5fP6ZlHL5o9D9\/f0flFLzQgjXGf4SkRrgRn8ftm23PVEUcXYeY8JT1NE\/GGN8x3EWx8bGfml5EleAT27lckOZdBopv+h5LbZtYwOZwRTJREytXncPq9UnAC1wonVkpdT8rVxuSGZvkhlM9QRelZSS\/htJgKHDanU+m83+JaVctgDK5fIjIYSbSac\/G9hSZjBFJp1GCOFezIJEpVKZBmallEgp2+a\/373jT98H4CvX5fboKABr6+s0ooikbXN\/YqLdcRiGGGNmK5XKC0trPSmEsFKpzg5l9iZ7e3uUSiXevH5N7SRkbX2d1ZUVSqUSTjbb4b+ot7TWk5YxZjydyXRMuHWsBzMzABwdHfHH7yusr60BUCgUKBQKHX7btnEcB2PMuEVzsXvq9ugok1NTAGxvb3N6esrw8DDfTT\/o8l5q6o5F86V0ddrSN\/fuMTAwQL1eZ2dnh6\/v3v3UMHMWUH1\/dvZRR7H4io2NDXzfp9Fo8PPTp2itr4NWLWAXmi\/lqra2tnj58lcA5ubmSCaTNBoNFhYWuryX6nctIcSmUqoLqrVmaWkJANd1mZmZ4cfHjwHwfZ9isdgFVUohhNhMSClXjTE\/hWFoXd7TnbdvefjwewCmpiYBuD8xQfXggChqEEWNDmgYhgAfpJSrxHGM53nPPc+LgyCI\/4uCIIg9z4s9z3sexzEWQD6ffwb4QRBQOwmvG0KXaichQRAA+BecJlRKuew4zqJS6vj48OBT021La83x4QFKqWPHcRZbudqOvlZsKaXmoyhywzAklUo1o+5KnkZRRBiGaK175um1yQ9YjuMAzcfR2hClFMDnJf9l\/Z9\/1L81r78oUzK1YgAAAABJRU5ErkJggg==","2":"iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpMwidZAAABWUlEQVQ4Ee2SS46CQBCGf8gAcgHFG+jGtfEWXIBHOBcKR+EScAQfG90RSGCGvyY9MtIuTFzMYippuqur6qO6qozPQfBGMd\/IEtQ\/8F7R2+0GLorqm9qv16vYlH6PAj7Gijqfz2fs93sYhoEwDLFcLsVE\/XQ6Icsy0eM4xmKxUGGya5tSVRWappHFYEIoCkZb27Yoy1Luxx8tcLVaYTabSYYMJrQoCtmpU2zbxnq9HrPkbAx1mAw2ry6XC9I0Rdd16Pv+23l4Ms\/8WRRF8DxvAtRmyFrN53MkSQLLsn41hbZnMNK1QBoYyEy5THPqpnkYw54Dj8cj8jyX4vOZYwBryknQyfTXgxedCavrWmJc14Xv+3AcR3Q25nA4\/HR\/DNYC1djw2YQEQYDNZiO1U1CODf0eRQvcbrfSFNVNDjbh7CobQigHerfbPfKgHZuJ1wsX2gxfiJ+4\/n3gF7OOrAbt6WEPAAAAAElFTkSuQmCC","3":"iVBORw0KGgoAAAANSUhEUgAAACcAAAAUCAMAAAA5k9QEAAAAllBMVEVHcEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0tbUhISHFxcYICAitr7EqKipKSkrMzMzHyMqIiouQkZO9vb0QEBB7e3tDRESlpaapq61qamvBw8Tk5ebe3t\/R0tMZGRo6Ojp\/gIGgoqRSUlLq6uuZmZnW1te3ubt2d3hf8fIfAAAAEXRSTlMAzFVEMRFmd7vumd2qbCKID4nBdwUAAADPSURBVCjPhdLXEoIwFATQBSIIVkKxACrdXv7\/50RCDQj7krk7hwyTBERa6KNZEIDIwhjTxDV+EdUhJRCUIQNQmKCOVNVntmzKedZkwLyoj1Eu3Me9KOQWg8haw9yZGXTjmLJCBZfi8+0+g06S0AOb57wTapimL7tgusK7qV7B\/a7cbch9vMg0t6MupO+n7XmnERcGtmsZAaWnQWfcfMfKFt92eo8PUFh\/uVq5P1psXvJu0nvFU+DPhu2QroPWZTL6suKUKqI\/ktb4yZnSfFFfkB8jKwCptUAAAAAASUVORK5CYII=","5":"iVBORw0KGgoAAAANSUhEUgAAABEAAAARCAYAAAA7bUf6AAAAAXNSR0IArs4c6QAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAAVRJREFUOBGtVDuugzAQXBwhIA1UUKWgoOMAnIETcJwchxNwEgokSiqQUtAEEL\/HWNongwJ6T8oWxti7w+CZtfZ6vdZ5nilNU2rblpIkIdd1qXu\/aVkW4hBCkHW\/U9M0MjcIAorjmMZxJMEA2ByGQSZgjgIUIo4AyMvznLIsI13X6fZ4PJ4o4gBoURTk+z45jkPrxsa0rF8GAOBAHdgLDMdQGZ0BcE1ZlqRtw4rzUL\/ACYZhyPOpqoqXdk\/s4wy1jckKWmdAuyrlhQEggoAKmAARG38JFQD1AjL+B+gIgHqpISZD35PneZLVFRv4A3nIZx9JEPjAME2q61pKeQUCNZCHfMVHeyd+UkkFVeVnQ35HnSt5cYiboz+qpjK6bfI+P\/0CqxBFkWwBtAJaQg1uEWHbtrou5wwA\/\/Rdd+kjqCW49RlJBYB\/pmk69VEYhvI60L5xn\/wAjtgb\/fA0ZZYAAAAASUVORK5CYII=","6":"iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAA6HWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgICAgICAgICAgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIgogICAgICAgICAgICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIKICAgICAgICAgICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIj4KICAgICAgICAgPHhtcDpDcmVhdGVEYXRlPjIwMTgtMDItMjdUMTQ6MTQ6MzgrMDQ6MDA8L3htcDpDcmVhdGVEYXRlPgogICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAxOC0wMi0yN1QxNDoxNjoxMSswNDowMDwveG1wOk1vZGlmeURhdGU+CiAgICAgICAgIDx4bXA6TWV0YWRhdGFEYXRlPjIwMTgtMDItMjdUMTQ6MTY6MTErMDQ6MDA8L3htcDpNZXRhZGF0YURhdGU+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTcgKFdpbmRvd3MpPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2UvcG5nPC9kYzpmb3JtYXQ+CiAgICAgICAgIDxwaG90b3Nob3A6Q29sb3JNb2RlPjM8L3Bob3Rvc2hvcDpDb2xvck1vZGU+CiAgICAgICAgIDx4bXBNTTpJbnN0YW5jZUlEPnhtcC5paWQ6MWNlZWE3YWMtNTIxMC02MjQ2LWFiMDQtZTA1YmEwYjljOTQ1PC94bXBNTTpJbnN0YW5jZUlEPgogICAgICAgICA8eG1wTU06RG9jdW1lbnRJRD5hZG9iZTpkb2NpZDpwaG90b3Nob3A6MzFlZDk3OGEtMWJhNy0xMWU4LTg0YTctZjA4OTdlNjEzNGM0PC94bXBNTTpEb2N1bWVudElEPgogICAgICAgICA8eG1wTU06T3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6OWFmYzkxOTgtOWNlNC1lZDQ4LThlNjYtNmFkMzdiNGFmOTQxPC94bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ+CiAgICAgICAgIDx4bXBNTTpIaXN0b3J5PgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+c2F2ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0Omluc3RhbmNlSUQ+eG1wLmlpZDo5YWZjOTE5OC05Y2U0LWVkNDgtOGU2Ni02YWQzN2I0YWY5NDE8L3N0RXZ0Omluc3RhbmNlSUQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDp3aGVuPjIwMTgtMDItMjdUMTQ6MTY6MTErMDQ6MDA8L3N0RXZ0OndoZW4+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpzb2Z0d2FyZUFnZW50PkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE3IChXaW5kb3dzKTwvc3RFdnQ6c29mdHdhcmVBZ2VudD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmNoYW5nZWQ+Lzwvc3RFdnQ6Y2hhbmdlZD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgICAgIDxyZGY6bGkgcmRmOnBhcnNlVHlwZT0iUmVzb3VyY2UiPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6YWN0aW9uPnNhdmVkPC9zdEV2dDphY3Rpb24+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDppbnN0YW5jZUlEPnhtcC5paWQ6MWNlZWE3YWMtNTIxMC02MjQ2LWFiMDQtZTA1YmEwYjljOTQ1PC9zdEV2dDppbnN0YW5jZUlEPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6d2hlbj4yMDE4LTAyLTI3VDE0OjE2OjExKzA0OjAwPC9zdEV2dDp3aGVuPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6c29mdHdhcmVBZ2VudD5BZG9iZSBQaG90b3Nob3AgQ0MgMjAxNyAoV2luZG93cyk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpjaGFuZ2VkPi88L3N0RXZ0OmNoYW5nZWQ+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICA8L3JkZjpTZXE+CiAgICAgICAgIDwveG1wTU06SGlzdG9yeT4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+NzIwMDAwLzEwMDAwPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjAwMDAvMTAwMDA8L3RpZmY6WVJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOlJlc29sdXRpb25Vbml0PjI8L3RpZmY6UmVzb2x1dGlvblVuaXQ+CiAgICAgICAgIDxleGlmOkNvbG9yU3BhY2U+NjU1MzU8L2V4aWY6Q29sb3JTcGFjZT4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjMwPC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjMwPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw\/eHBhY2tldCBlbmQ9InciPz7HmtNXAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAjWSURBVHjanFd9bFPXFf\/d9\/zsZ\/v5ObZfAnbIUpI0fCxMhGlJkxaNKpFAKkqntUIIaYRJJR9FiEGoJqoOov1RMVE1UxvSsoIqbVJVCoJuomVlypYh8aERWEoZ6dwSlYJxkmcndj7s5\/d19k9s4TZM64509a7ufff+zjn3nHN\/l+HRwhhjICIAIAAIBoNuv9\/v1XVdBCAA4Fwul+F2u\/XZ2VnNNM2ZiYkJ27Is\/F\/CGGMcxzHGGHM6nS5FUb5XWVnZuHPnzhey2ewJIjpPRKNEdJeI\/kVEf83lcr+bn5\/\/6c6dO6uXL1\/u5TjuO2MyQRB4nuedHo9naWtra9ulS5fO0oJkMhlSVZXi8TjFYjGKx+Okqipls9n8Lyki+k1XV9fampqaPDr7FtA3+zzPcwAckUjk+z09PZ179uzZAcD54MEDOxqN2oODg45bt25hamoKuq7D5XIhGAyivr4ejY2NZl1dHR+JRBiADBHt37Jlyx9Onz49t7A\/LaYAA+AAEFyzZk3LtWvXPiYimp6eppMnTxotLS3k8\/koHA5TRUUFVVZWFlpFRQUtXbqUZFmmTZs20ZkzZ\/RUKpX3QP\/WrVuVR1rO87wAwBeJRDZcuHDhBhHR119\/Tdu3bydJkigSiVB1dTVVVVU9slVXV1MkEiFZlqmjo4NisVge\/PiWLVskp9NZfKZOp5MnIpdlWSuOHj36i87Ozp89ePAA3d3duHDhAsrLy\/PR\/T9LPB5HW1sb+vr6EA6HAeClcDjcNz4+bgEAD4C5XC53LpdbsmHDhrY33nhjXyaTsXt6etiHH36IioqK7wwKAH6\/H8PDw0gmk1i\/fj253e6GL7\/88tytW7cmLctinCAIfCaTkWVZXnfgwIHNAHDmzBnr5MmTWLZsGWzbBsdxME0TiUQCqqpC13Xk04XjOORyOUxOTiKRSMA0TTDGYNs2IpEI3nvvPZw7d44AlLz99tsvSJIkAiBeFEUvEZU3Nze39Pb2botGo+zQoUN8JpOBw+EAABiGAZ\/Ph40bN2Lt2rWIxWKYmpqCJEmYnp6Goihoa2tDbW0tVFWFpmkFxQRBwMTEBGtubkYgEPjh\/fv3\/zQyMhIHgDJFUX5y6tSpvxERvf766yQIAtXU1BSCxuv1Und3dz5QaGBggMLhMImiSEuWLKFjx44V5trb20mW5aKA83g8dOzYMbIsi4joV5WVlW4OgOx2u6uam5t\/MDs7i88++wyhUAi2bRfOi4gK1gNAd3c3enp6oCgK9u\/fj46OjsJ\/PM8XnTURIRAIYGRkBHNzc7Asq9Xr9fodAEoFQSiNRCKusbExXLt2DS6Xq2hxMBjERx99hJqaGuzevRuMMXR2dqK5uRn19fUAANM00dfXh6GhIfj9\/qL1DocDw8PDmJ2dhSzL6zRN8zgACBzHuQF4NU3D5OQkvF5v0UJRFJFOp3H48GHkcjns2LEDpaWlaGpqAgCMj4\/j+PHj6O\/vBxFBluUij\/E8j\/v370PXdQCQNE1zcwAEp9MpAIBt24umjm3bCAQCSCQSePPNN3H37t2i+Tt37uDo0aNIp9MoKSkpAs2LpmmwLIsWMoHjAIg8z3vzqbHYrcJxHKamphAMBrFnzx5UV1cXza9cuRK7d++GLMtIpVKL7uFwOMBYoWKSAwBpmjYDICMIgsfr9cKyrKIgyeVy8Pv92Lt3L3bt2lUY+\/zzz7F69WqEQiG8\/PLLcLlceOutt5DL5SAIQpHHFEWB0+lkAFIALA6Akc1mM6qqpgOBAFavXg3DMIq0TSaT2Lx5cwEUAAYGBvD888\/jnXfeKYz19PTg6aefRiqVKlpvWRaqqqrgdrsxMzMzbZqmwQGYm5mZyV66dGkmFArhySefRCqVetgtYIxB07Qi0CNHjmBsbAyvvvoqTpw4UeSdh13NGMPc3BwaGhrg9\/uh6\/q\/LcvK8oyxkK7rwVwuV7J169aVbrcbn3zyCUzTLGwgiiLGx8cRjUYxNDSEd999F3Nzc1i2bBnS6TQ+\/fRTxGIxnD17FpcvXy6KFdu2IUkSXnnlFZSXl2Pfvn29w8PD\/2QAKgH8SFGUpqtXr25\/7LHHlL1792JgYADLly8v1Gpd15FIJArnJYpiYS6bzSKZTILneYRCIQiCACICx3G4d+8edu3ahSNHjoDjuIQkST+en5+\/zXs8HrIsS9Y0zZ9MJtlzzz234vHHH8fo6Cii0SgkSSoASJIEn88HnucLaZevaj6fD5IkFSxljCGRSKC1tRW9vb0IBALo6Oj49cjIyN9N09R4APZCDZVHR0edq1atWvrUU08Famtrcf78eaiqCp\/P952uRo7joKoqysvL0d\/fjxUrVuDmzZt\/6erqOmwYxgQAxtu2TR6PxzAMg7dt2zs8PGw0NjaWPvHEE3JDQwO++OIL3LhxA5IkfasOL8IUYZom7t27h9bWVvT19WHdunWIx+NT7e3tB8bHx0eIyCIixjPGGBHZRKQzxrjp6WnH7du3cy0tLUvXrFnjbWhogG3b+OqrrxCPx+FwOMDzfCHq89xb0zQkEgkoioJt27bh4MGDqKurg6qq0+3t7b1DQ0Mf27adyReQh4mek+O4CgAtAF6qq6v7\/fvvv3+HiEjXdbp48SIdPHiQNm7cSCUlJSSKIkmSRKIoUiAQoGeeeYYOHTpEV65cIV3XiYhocHBwpKmp6ecAyvJsJ0\/42EPsjwA4GWNlRFQLYFUwGKzatGlTzWuvvbY+HA4HACAWi2FychKGYdiWZVkcx\/Eul4srKytDJBIBAMzOzqovvvjiB4ODg3+Ox+P\/ADAFwPxvFBcAnAsaNgDYBuCXVVVVv3322Wf\/ePHixZtElKTFJXH9+vWxzs7OD2pra7sA1AMoWdiPfZPaskXAyeFwOJxOpzuTyZQu5LkCoLSsrEwpLS1dIoqijzFGjDHONE3dMIyUZVnJdDqtxuPxO0QUdblcKcuycqZpGotZyh71WFsgbAIACYAPQACAZ6EvALABcAB0AGkA8wCmF75ZjuN0Iip69D0s\/xkAalh5iwp88nkAAAAASUVORK5CYII="},"homePageUrl":"https:\/\/www.cdi.org.in\/","isPreview":"","convertedIdsReverse":[],"dontShowPopupExpireTime":"365","conditionalJsClasses":[]};
var SGPB_JS_PACKAGES = {"packages":{"current":1,"free":1,"silver":2,"gold":3,"platinum":4}};
var SGPB_JS_PARAMS = {"ajaxUrl":"https:\/\/www.cdi.org.in\/wp-admin\/admin-ajax.php","nonce":"033955518d"};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/popup-builder/public/js/PopupBuilder.js?ver=3.0.7'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.70'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var wc_add_to_cart_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","wc_ajax_url":"\/?wc-ajax=%%endpoint%%","i18n_view_cart":"View cart","cart_url":"https:\/\/www.cdi.org.in\/book-an-appointment-doctor-list\/","is_cart":"","cart_redirect_after_add":"yes"};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=3.5.9'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/woocommerce-quantity-increment/assets/js/wc-quantity-increment.min.js?ver=4.9.18'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/spin.min.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/ladda.min.js?ver=16.3'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var BooklyCustomerProfileL10n = {"csrf_token":"ad967ed6f4","show_more":"Show more"};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-addon-pro/frontend/modules/customer_profile/resources/js/customer_profile.js?ver=1.1'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/hammer.min.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/jquery.hammer.min.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/picker.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/picker.date.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/intlTelInput.min.js?ver=16.3'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var BooklyL10n = {"ajaxurl":"https:\/\/www.cdi.org.in\/wp-admin\/admin-ajax.php","csrf_token":"ad967ed6f4","today":"Today","months":["January","February","March","April","May","June","July","August","September","October","November","December"],"days":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"daysShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"nextMonth":"Next month","prevMonth":"Previous month","show_more":"Show more"};
/* ]]> */
</script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/bookly-responsive-appointment-booking-tool/frontend/resources/js/bookly.min.js?ver=16.3'></script>
<script type='text/javascript' src='https://www.cdi.org.in/wp-content/plugins/js_composer/assets/js/vendors/woocommerce-add-to-cart.js?ver=5.5.2'></script>
<link rel='https://api.w.org/' href='https://www.cdi.org.in/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.cdi.org.in/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.cdi.org.in/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.9.18" />
<meta name="generator" content="WooCommerce 3.5.9" />
<link rel='shortlink' href='https://www.cdi.org.in/?p=1123' />
<link rel="alternate" type="application/json+oembed" href="https://www.cdi.org.in/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.cdi.org.in%2Fdepartment%2Fdiabetology%2F" />
<link rel="alternate" type="text/xml+oembed" href="https://www.cdi.org.in/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.cdi.org.in%2Fdepartment%2Fdiabetology%2F&#038;format=xml" />
	<noscript><style>.woocommerce-product-gallery{ opacity: 1 !important; }</style></noscript>
	<meta name="generator" content="Powered by WPBakery Page Builder - drag and drop page builder for WordPress."/>
<!--[if lte IE 9]><link rel="stylesheet" type="text/css" href="https://www.cdi.org.in/wp-content/plugins/js_composer/assets/css/vc_lte_ie9.min.css" media="screen"><![endif]--><style type="text/css">.broken_link, a.broken_link {
	text-decoration: line-through;
}</style><link rel="icon" href="https://www.cdi.org.in/wp-content/uploads/2018/09/cropped-apple-icon-114x114-32x32.png" sizes="32x32" />
<link rel="icon" href="https://www.cdi.org.in/wp-content/uploads/2018/09/cropped-apple-icon-114x114-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="https://www.cdi.org.in/wp-content/uploads/2018/09/cropped-apple-icon-114x114-180x180.png" />
<meta name="msapplication-TileImage" content="https://www.cdi.org.in/wp-content/uploads/2018/09/cropped-apple-icon-114x114-270x270.png" />
</head>	
<?php include 'header3.php'?>

<!-- Csgve Page Title, Csgve Parallax -->
<div class="csgve-page-title csgve-parallax padding-none " style="">
		<div class="csgve-overlay-pattern" style="background-color:rgba(52,129,219,0.5);"></div>
		<div class="container">
		<div class="row">
			<div class="col-md-8"><h2 class="page-title"><?php echo($_GET['a']); ?></h2></div>
			<div class="col-md-4">
				<nav aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs"></nav>			</div>
		</div>
	</div>
</div>


<div class="csgve-mid-wrap csgrve-dept-sngl  right-sidebar" style="">

	<div class="container">

	<div class="row">

		
		<div class="col-md-9 csgve-content-area csgve-primary">

			<div class="">

		    <div class="dental-care-wrap">

					<div class="vc_row wpb_row vc_row-fluid csgve-dhav-dotted"><br />
<div class="wpb_column vc_column_container text-default vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><br />
<div class="info-title gdregdregregre csgve-title-61b0277dcc902-meet-our-best-diabetologist-doctors-in-pune info-title-uline">Meet Our Best <?php echo($_GET['a']); ?>ist Doctors in Pune</div><br />
    <!-- Doctors Start
    <div class="head-departments doctor-style-one   csgve-doct-61b0277dcc9a9 ">
    <div class="row">      <div class="col-md-4 col-sm-6">
              <div class="csgve-item doctors-item">
                    <div class="csgve-image"><a href="#"><img src="https://www.cdi.org.in/wp-content/uploads/2017/10/Dr-AG-Unnikrishnan-thumb-1.jpg" alt=""></a>              <div class="icon-trigger"><span></span></div>
               </div>
          
          <div class="doctor-info">
            <div class="doctor-bg-change">
              <h4 class="doctor-name"><a href="#">Dr. A. G. Unnikrishnan</a></h4>
              <h5 class="doctor-designation">Endocrinologist/Diabetologist</h5>
                            <div class="csgve-btn-group medic-button"><a class="csgve-btn csgve-small-btn csgve-gray-border-btn" href="#">Book an Appointment</a></div>
                          </div>
                           <div class="doctor-contact-info">
                            </div>
                                  </div>
        </div>
      </div>
          <div class="col-md-4 col-sm-6">
              <div class="csgve-item doctors-item">
                    <div class="csgve-image"><a href="#"><img src="#" alt=""></a>              <div class="icon-trigger"><span></span></div>
               </div>
          
          <div class="doctor-info">
            <div class="doctor-bg-change">
              <h4 class="doctor-name"><a href="#">Dr. Vedavati Purandare</a></h4>
              <h5 class="doctor-designation">Physician and Diabetologist</h5>
                            <div class="csgve-btn-group medic-button"><a class="csgve-btn csgve-small-btn csgve-gray-border-btn" href="#">Book An Appointment</a></div>
                          </div>
                           <div class="doctor-contact-info">
                              <div class="doctor-contact-item">
              <span>                                 <span class="hover-icon-mail"><i class="fa fa-envelope-o" aria-hidden="true"></i>reception@cdi.org.in</span>                               </span>              </div>
                          <div class="doctor-contact-item">
              <span>                                                   <span class="hover-icon-phone"><i class="fa fa-phone" aria-hidden="true"></i> Mon - Sat ( 10:00 AM - 3:30 PM )</span>               </span>              </div>
                             </div>
                                  </div>
        </div>
      </div>
          <div class="col-md-4 col-sm-6">
              <div class="csgve-item doctors-item">
                    <div class="csgve-image"><a href="#"><img src="https://www.cdi.org.in/wp-content/uploads/2021/03/DrManish.jpg" alt=""></a>              <div class="icon-trigger"><span></span></div>
               </div>
          
          <div class="doctor-info">
            <div class="doctor-bg-change">
              <h4 class="doctor-name"><a href="#">Dr. Manish Bothale</a></h4>
              <h5 class="doctor-designation">Diabetologist</h5>
                            <div class="csgve-btn-group medic-button"><a class="csgve-btn csgve-small-btn csgve-gray-border-btn" href="#">Book an Appointment</a></div>
                          </div>
                           <div class="doctor-contact-info">
                              <div class="doctor-contact-item">
              <span>                                 <span class="hover-icon-mail"><i class="fa fa-envelope-o" aria-hidden="true"></i>reception@cdi.org.in</span>                               </span>              </div>
                          <div class="doctor-contact-item">
              <span>                                                   <span class="hover-icon-phone"><i class="fa fa-phone" aria-hidden="true"></i> Mon - Sat (9:00 AM to 5:00 PM)</span>               </span>              </div>
                             </div>
                                  </div>
        </div>
      </div>
          <div class="col-md-4 col-sm-6">
              <div class="csgve-item doctors-item">
                    <div class="csgve-image"><a href="#"><img src="https://www.cdi.org.in/wp-content/uploads/2018/11/dr.Aditi-th.jpg" alt=""></a>              <div class="icon-trigger"><span></span></div>
               </div>
          
          <div class="doctor-info">
            <div class="doctor-bg-change">
              <h4 class="doctor-name"><a href="#">Dr. Shraddha Lumpatki</a></h4>
              <h5 class="doctor-designation">Consultant Physician</h5>
                            <div class="csgve-btn-group medic-button"><a class="csgve-btn csgve-small-btn csgve-gray-border-btn" href="#">Book an Appointment</a></div>
                          </div>
                           <div class="doctor-contact-info">
                              <div class="doctor-contact-item">
              <span>                                 <span class="hover-icon-mail"><i class="fa fa-envelope-o" aria-hidden="true"></i>reception@cdi.org.in</span>                               </span>              </div>
                          <div class="doctor-contact-item">
              <span>                                                   <span class="hover-icon-phone"><i class="fa fa-phone" aria-hidden="true"></i> Mon - Sat (9:00 AM to 5:00 PM)</span>               </span>              </div>
                             </div>
                                  </div>
        </div>
      </div>
    </div>    </div> -->
    <!-- Doctors End -->

    </div></div></div><br />
</div>
<div class="vc_row wpb_row vc_row-fluid csgve-dhav-dotted"><div class="wpb_column vc_column_container text-default vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper">
	<div  class="wpb_single_image wpb_content_element vc_align_left">
		
		<figure class="wpb_wrapper vc_figure">
			<div class="vc_single_image-wrapper vc_box_rounded  vc_box_border_grey"><img width="850" height="490" src="https://www.cdi.org.in/wp-content/uploads/2018/09/Diabetology-new.jpg" class="vc_single_image-img attachment-full" alt="" srcset="https://www.cdi.org.in/wp-content/uploads/2018/09/Diabetology-new.jpg 850w, https://www.cdi.org.in/wp-content/uploads/2018/09/Diabetology-new-300x173.jpg 300w, https://www.cdi.org.in/wp-content/uploads/2018/09/Diabetology-new-768x443.jpg 768w" sizes="(max-width: 850px) 100vw, 850px" /></div>
		</figure>
	</div>
</div></div></div></div>
<div class="vc_row wpb_row vc_row-fluid csgve-dhav-dotted"><div class="wpb_column vc_column_container text-default vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="info-title  csgve-title-61b0277dcf62b-diabetology info-title-uline"><?php echo($_GET['a']); ?></div>
	<div class="wpb_text_column wpb_content_element " >
		<div class="wpb_wrapper">
			
		</div>
	</div>
<p>Full time consultants specialized in Diabetes care and metabolic disorder management e.g. dyslipidemia, thyroid diseases, obesity etc.</p>
<p>We specialize in all aspects of diabetes management including <strong><em>Type 1 Diabetes</em></strong> (mostly found in children), <strong><em>Type 2 Diabetes</em></strong> (mostly found in adults), Gestational Diabetes (Diabetes in Pregnancy), and diagnosing and treating diabetes complications earliest so that progression would be halted sooner.</p>
<p>Consultation time – 8:30 am to 5:30 pm except for Sundays &amp; Limited holidays</p>
<p>Our consultants spend quality time with patients understanding their problems, alleviating their anxiety and fears, empowering them with the knowledge to live positively with Diabetes.</p>
<p><strong>Services offered:</strong></p>
<ul>
<li>Detailed history</li>
<li>Complete physical evaluation including foot examination</li>
<li>Detail explanation of the patient’s current health status</li>
<li>Diabetes education including lifestyle modification</li>
<li>Treatment plan relevant to patient needs</li>
<li>Patient care is not confined to consulting rooms/office hours, but we are in constant touch with patients through email/mobile.</li>
</ul>
<p>Working in coordination with other state-of-the-art support departments like Cardiology, Neurology, Nephrology, Ophthalmology, Radiology, Physiotherapy and Yoga, the Diabetology unit of Chellaram Diabetes Institute aspires to become a Centre of Excellence and a referral center in <strong>Diabetes</strong>.</p>
<p>Book Appointment Now to know more about <a href="#">Chellaram Hospital</a> – <strong>Best Diabetology Hospital in Pune</strong></p>
<p>&nbsp;</p>
<p>&nbsp;<br />
<div class="vc_row wpb_row vc_row-fluid csgve-dhav-dotted"></div><div class="wpb_column vc_column_container text-default vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"></div></div></div><h2 style="text-align: left;font-family:Noto Sans;font-weight:400;font-style:normal" class="vc_custom_heading" >Diabetes Health Check-up Package</h2><div class="woocommerce columns-4 "><ul class="products columns-4">
<li class="post-4946 product type-product status-publish has-post-thumbnail product_cat-health-packages first instock sale sold-individually shipping-taxable product-type-external">
	<a href="#" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
	<span class="onsale">Sale!</span>
<img width="270" height="200" src="https://www.cdi.org.in/wp-content/uploads/2018/10/Comprehensive-Diabetes-Package-Fasting.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" /><h2 class="woocommerce-loop-product__title">COMPREHENSIVE DIABETES HEALTH CHECK-UP FASTING</h2>
	<span class="price"><del><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#8377;</span>16,235.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#8377;</span>9,700.00</span></ins></span>
</a><a href="#" data-quantity="1" class="button product_type_external" data-product_id="4946" data-product_sku="" aria-label="Book Now" rel="nofollow">Book Now</a></li>
</ul>
</div></div></div></div></div>

		    </div>

			</div>Blog Div

		</div>

		
<div class="col-md-3 csgve-secondary  ">
	<div id="widget-departments-2" class=" csgve-widget widget-departments"><div class=" nav-notenabled-child departments-wrap"><h4 class="department-wrap-title">Specialties</h4><div class="menu-specialties-container"><ul id="menu-specialties" class="menu csgve-sidenav"><li id="menu-item-2488" class="menu-item menu-item-type-post_type menu-item-object-department current-menu-item menu-item-2488"><a href="https://www.cdi.org.in/department/diabetology/">Diabetology</a></li>
<li id="menu-item-2489" class="menu-item menu-item-type-post_type menu-item-object-department menu-item-2489"><a href="#">Cardiology</a></li>
<li id="menu-item-2490" class="menu-item menu-item-type-post_type menu-item-object-department menu-item-2490"><a href="#">Nephrology</a></li>
<li id="menu-item-2491" class="menu-item menu-item-type-post_type menu-item-object-department menu-item-2491"><a href="#">General &#038; Laparoscopic Surgery</a></li>
<li id="menu-item-2492" class="menu-item menu-item-type-post_type menu-item-object-department menu-item-2492"><a href="#">Diabetic Foot Care</a></li>
<li id="menu-item-2493" class="menu-item menu-item-type-post_type menu-item-object-department menu-item-2493"><a href="#">Ophthalmology</a></li>
</ul></div></div></div><div id="vt-text-widget-1" class=" csgve-widget vt-text-widget"><div id="csgve-widget-placeholder-2" class="widget-opening-hours"><div class="valuable-status-item cus csgve-service-list-61b0277de4c13 " ><div class="csgve-overlay-pattern"></div><h3 class="status-title">Open 24 Hours</h3><ul></ul></div></div></div><div id="vt-text-widget-2" class=" csgve-widget vt-text-widget"><div id="csgve-widget-placeholder-3" class="csgve-widget widget-emergency"><div class="emergency-title"> Contact Us</div><a href="tel:020 66839 777 / 877">020 66839 777 / 877</a></div>
</div><div id="wpforms-widget-2" class=" csgve-widget wpforms-widget"><div class="wpforms-container wpforms-container-full" id="wpforms-8157"><form id="wpforms-form-8157" class="wpforms-validate wpforms-form" data-formid="8157" method="post" enctype="multipart/form-data" action="/department/diabetology/" data-token="37d15604e9f99656a85ac86d5f7b9cfd"><noscript class="wpforms-error-noscript">Please enable JavaScript in your browser to complete this form.</noscript><div class="wpforms-field-container"><div id="wpforms-8157-field_4-container" class="wpforms-field wpforms-field-name" data-field-id="4"><label class="wpforms-field-label" for="wpforms-8157-field_4">Name <span class="wpforms-required-label">*</span></label><input type="text" id="wpforms-8157-field_4" class="wpforms-field-large wpforms-field-required" name="wpforms[fields][4]" required></div><div id="wpforms-8157-field_1-container" class="wpforms-field wpforms-field-email" data-field-id="1"><label class="wpforms-field-label" for="wpforms-8157-field_1">Email <span class="wpforms-required-label">*</span></label><input type="email" id="wpforms-8157-field_1" class="wpforms-field-large wpforms-field-required" name="wpforms[fields][1]" required></div><div id="wpforms-8157-field_3-container" class="wpforms-field wpforms-field-number" data-field-id="3"><label class="wpforms-field-label" for="wpforms-8157-field_3">Mobile <span class="wpforms-required-label">*</span></label><input type="number" pattern="\d*" id="wpforms-8157-field_3" class="wpforms-field-large wpforms-field-required" name="wpforms[fields][3]" required></div><div id="wpforms-8157-field_2-container" class="wpforms-field wpforms-field-textarea" data-field-id="2"><label class="wpforms-field-label" for="wpforms-8157-field_2">Message <span class="wpforms-required-label">*</span></label><textarea id="wpforms-8157-field_2" class="wpforms-field-medium wpforms-field-required" name="wpforms[fields][2]" required></textarea></div></div><div class="wpforms-submit-container" ><input type="hidden" name="wpforms[id]" value="8157"><input type="hidden" name="wpforms[author]" value="1"><input type="hidden" name="wpforms[post_id]" value="1123"><button type="submit" name="wpforms[submit]" class="wpforms-submit " id="wpforms-submit-8157" value="wpforms-submit" aria-live="assertive" data-alt-text="Sending..." data-submit-text="Submit">Submit</button></div></form></div>  <!-- .wpforms-container --></div></div><!-- #secondary -->

	</div>

	</div>

</div><!-- Content Area -->

<?php include 'footer.php'?>


</body>
</html>
